### ISSUE TITLE
Missing imageStream, improve docs

### ISSUE THREAD

**Issue by jprukner** [openshift/cakephp-ex#13]
I followed instructions here: https://github.com/openshift/cakephp-ex and at step 4 I got an error:
Error from server: imageStream "php" not found
There aren't any image streams. I had to create them. Previous step should be something like:
You have to create php image stream first. 
$ oc create -f /data/src/github.com/openshift/origin/examples/image-streams/image-streams-centos7.json -n openshift

**Comment by bparees** [comment]
not sure if your issue pre-dated the current state of the readme, but it now says this immediately before the steps:

```
These steps assume your OpenShift deployment has the default set of ImageStreams defined.  Instructions for installing the default ImageStreams are available [here](http://docs.openshift.org/latest/admin_guide/install/first_steps.html).  If you are defining the set of ImageStreams now, remember to pass in the proper cluster-admin credentials and to create the ImageStreams in the 'openshift' namespace.
```

so closing this.
