### ISSUE TITLE
Update templates after CakePHP and SCL 2.3 updates merged

### ISSUE THREAD

**Issue by luciddreamz** [openshift/cakephp-ex#50]
The OpenShift template files currently reference PHP:5.6 and MySQL 5.6. Once CakePHP is updated to 2.8+ and openshift/origin/pull/12005 is merged, we should update these templates to reference PHP:7.0 and MySQL 5.7 instead. Note that MySQL 5.7 likely requires other template updates as well.

**Comment by bparees** [comment]
the mysql changes are here:
https://github.com/openshift/cakephp-ex/pull/49

the php changes obviously will need to wait until the php imagestream changes are in.
