### ISSUE TITLE
MySQL don't up with PHP Service!

### ISSUE THREAD

**Issue by ioricloud** [openshift/cakephp-ex#62]
hi

I have a problem about PHP service with MySQL Database. When create PHP with MySQL, none Service stay up, but when I create PHP only, PHP up normally. I want to create with the two services.

`Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "mysql-3-5iqui"/"servicejs". list of unattached/unmounted volumes=[mysql-data]`

and this

`Unable to mount volumes for pod "mysql-3-5iqui_servicejs(1437caee-f3dd-11e6-be40-0e3d364e19a5)": timeout expired waiting for volumes to attach/mount for pod "mysql-3-5iqui"/"servicejs". list of unattached/unmounted volumes=[mysql-data]`

**Comment by bparees** [comment]
How are you creating the mysql database?  are you using one of our templates?  which one?

what openshift enviornment are you using (online dev preview?  your own cluster?  if it's your own cluster, how did you bring it up?)

most likely you have instantiated the persistent template and do not have any persistent volumes available in your cluster.

**Comment by ioricloud** [comment]
thanks for answer bparees. I am using template in openshift origin. How you wrote, I am instantiating template but PHP nor MySQL.
What can I to do?

**Comment by bparees** [comment]
can you point me to the template you're using?

have you instantiated anything else in your project?  you only get 2 volumes, it's possible you're already using the 2 you get.

**Comment by ioricloud** [comment]
![captura de tela de 2017-02-15 17 19 26](https://cloud.githubusercontent.com/assets/150522/23048115/8d8de940-f492-11e6-9451-74f620b86f32.png)
cakephp with mysql

**Comment by bparees** [comment]
I have opened a bug for your issue here:
https://bugzilla.redhat.com/show_bug.cgi?id=1423066

please subscribe to it as we'll investigate it from there.
